#!/bin/sh
set -eu

for brightness in /sys/class/backlight/*/brightness; do
    [ -e "$brightness" ] || continue
    chgrp video "$brightness"
    chmod g+w "$brightness"
done

for cpufreq in /sys/devices/system/cpu/cpufreq/policy*/scaling_max_freq /sys/devices/system/cpu/cpufreq/policy*/scaling_governor /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    [ -e "$cpufreq" ] || continue
    chmod a+w "$cpufreq"
done
