#!/bin/sh
set -eu

if [ -r /etc/meow-os/display.conf ]; then
    . /etc/meow-os/display.conf
fi

export QT_QPA_PLATFORM="${MEOW_QPA_PLATFORM:-linuxfb:fb=/dev/fb0}"
case "${QT_QPA_PLATFORM}" in
    linuxfb*) export QT_QUICK_BACKEND="${QT_QUICK_BACKEND:-software}" ;;
    eglfs*)
        unset QT_QUICK_BACKEND
        export QT_QPA_EGLFS_KMS_CONFIG="${MEOW_EGLFS_KMS_CONFIG:-/opt/meow-os/eglfs-kms.json}"
        export QT_QPA_EGLFS_HIDECURSOR="${MEOW_EGLFS_HIDECURSOR:-1}"
        ;;
esac

exec /opt/meow-os/meow-os
